### ISSUE TITLE
`js_module_root` not working, impossible to use absolute paths in imports

### ISSUE THREAD

**Issue by dmitrysteblyuk** [google/closure-compiler#3628]
`js_module_root` seems to have stopped working since some version.
The compiler gives this error:
```
ERROR - [JSC_MISSING_ENTRY_ERROR] required entry point "src/a.js" never provided
```

Now it's impossible to have absolute paths in imports.
Latest working version that I know of is `20170521.0.0`.

I created a reproduction repo https://github.com/dmitrysteblyuk/js_module_root-bug-repro

Here's the command I'm running:

```
java -jar ./node_modules/google-closure-compiler-java/compiler.jar \
  --compilation_level=ADVANCED \
  --language_in=ES6_STRICT \
  --language_out=ES5 \
  --module_resolution=NODE \
  --entry_point=src/a.js \
  --js_module_root=src \
  --js=src/a.js \
  --js=src/b.js \
  --js_output_file=dist/index.js
```

And the files I'm compiling.
```
// src/a.js
// Works fine if I remove js_module_root and replace this to './b'
import {doSomething} from 'b';

doSomething();
```
```
// src/b.js
export function doSomething () {
  console.log('okay');
}

export function willBeStripped () {
  console.log('right');
}
```

**Comment by dmitrysteblyuk** [comment]
As a workaround one can use yarn workspaces (there will be a symlink to source directory in `node_modules`).
`js_module_root` won't be needed in this case.
Also `entry_point` will be `node_modules/src/a.js`.

**Comment by nreid260** [comment]
Does it work if you pass an absolute path for the root?

**Comment by dmitrysteblyuk** [comment]
> Does it work if you pass an absolute path for the root?

not really, but it gives a different error:
```
src/a.js:2: ERROR - Failed to load module "b"
import {doSomething} from 'b';
^
```
Which is the same btw if I give a non-existing module root, or none at all.

**Comment by nreid260** [comment]
@ChadKillingsworth Do you have any ideas?

**Comment by ChadKillingsworth** [comment]
My internal project is a bit behind on compiler versions, but I definitely use this flag. Let me try updating and see if I can recreate the problem. If so, I can use git bisect to find what introduced the issue.

**Comment by dmitrysteblyuk** [comment]
ChadKillingsworth, thank you for looking into this! Could you please share the version you're using, i'd like to try it too.

**Comment by ChadKillingsworth** [comment]
I'm using version 20191027.0.0 right now.

**Comment by dmitrysteblyuk** [comment]
I kinda made it work (for both versions - current and the one you mentioned).
I still cannot use absolute paths, but if i specify instead a **relative** path, then the js_module_root is being applied (and code compiles only with it).
```
java -jar ./node_modules/google-closure-compiler-java/compiler.jar \
  --compilation_level=ADVANCED \
  --language_in=ES6_STRICT \
  --language_out=ES5 \
  --module_resolution=NODE \
  --entry_point=./a.js \
  --js=./a.js \
  --js=./src/b.js \
  --js_output_file=dist/index.js \
  --js_module_root=./src
```
Files are the same but i had to change their location to test this:
```
./a.js
import {doSomething} from './b'; // <- relative paths is important here
doSomething()
```
```
./src/b.js
export const doSomething = ...
```

**Comment by ChadKillingsworth** [comment]
Looking at your original example, you aren't actually using absolute paths.

```js
// src/a.js
// Works fine if I remove js_module_root and replace this to './b'
import {doSomething} from '/b.js'; // an absolute path as a leading '/'

doSomething();
```

Without either a `'/', './' or '../', your path is a bare module specifier. Bare module specifiers are only valid with the NODE module resolution algorithm and would be looked for in the appropriate node_modules/ path.

**Comment by dmitrysteblyuk** [comment]
Oh I see. Never used imports with a leading slash, but it's probably even better as it avoids confusion with node modules (as long as webpack/node understand them).
Thank you so much for explanation!

**Comment by wdiestel** [comment]
Also it appears that entry_point has to be given as path *relative* to module_root. I did not found out how to debug such dependency issue neither is appears to be well documented in the help screen.
