### ISSUE TITLE
--jscomp_error=* includes lint about not relying on @override to copy typings

### ISSUE THREAD

**Issue by vapier** [google/closure-compiler#4275]
this seems to be a regression between v20201102 & v20201207.  here's an example:
```js
class foo {
  /**
   * Delete everything in this storage.
   *
   * @return {!Promise<void>} When clearing has completely.
   */
  async clear() {}
}

class fooBar extends foo {
  /** @override */
  async clear() {
    return new Promise((resolve) => {
      resolve();
    });
  }
}
```

in version v20201102 and older, we see no errors:
```
$ closure-compiler --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20201102
$ closure-compiler --jscomp_error='*' --checks-only test.js 
```

but after upgrading to v20201207 (v20250820 behaves the same), we see:
```
$ closure-compiler --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20201207
$ closure-compiler --jscomp_error='*' --checks-only test.js 
test.js:12:8: ERROR - [JSC_MISSING_RETURN_JSDOC] Function with non-trivial return must have JSDoc indicating the return type. Please see go/tsjs-problematic-patterns for why @overrides require explicit @return types..
  12|   async clear() {
              ^^^^^^^^^
  13|     return new Promise((resolve) => {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  15|     });
      ^^^^^^^
  16|   }
      ^^^

1 error(s), 0 warning(s), 94.8% typed
```

copying the typing info by hand makes it go away, but the documentation says this isn't necessary:
> https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#override
> If no other annotations are included, the method or property automatically inherits annotations from its superclass.

i'm guessing this is commit 777ab366ab0deaf4bbfc56523cbe3afe0aae63aa by @rishipal.  the associated internal bug suggests this change was made because of a bug in [Clutz](https://github.com/angular/clutz) -- it didn't actually implement the `@override` semantics.  i grok that maybe for internal Google code, since JS->TS was a temporary migration, forcing people to duplicate typing was reasonable, but i don't know why that policy decision was made in the external closure-compiler version.

**Comment by brad4d** [comment]
Your repro specifically uses async functions. Was that necessary, or do you have the same problem with normal functions?

We suspect that we intentionally changed the behavior to always require explicit type information on overriden functions. We'll need to see if we can find that information and update the documentation appropriately.

**Comment by brad4d** [comment]
@blickly has agreed to look into this. Thanks, Ben.

**Comment by vapier** [comment]
It happens on non-async too.  I just grabbed the first set of failures and reduced it down.

**Comment by lauraharker** [comment]
Oh, I think I see what happened -

The behavior of the actual type inference code hasn't changed - the compiler does still try and infer the overridden type. (This was because inside Google, while we wanted to discourage people from relying on the inference, we had to give up on first actually fixing all the missing override types because it proved harder than we thought.)

Inside google I think we just didn't realize this would be an issue, because `JSC_MISSING_RETURN_JSDOC` is only enabled in the linter. So there are still a lot of existing violations that are ignored until someone is actually editing that code.

Maybe the fix is to have `--jscomp_error='*'` not turn on JSC_MISSING_RETURN_JSDOC in the OSS version? I'm surprised it includes lint checks, I had previously thought we explicitly included linter checks even from `--jscomp_error=*`.

**Comment by lauraharker** [comment]
We should figure out what our story is for lint checks in the OSS compiler build

**Comment by rishipal** [comment]
+1, confirming the intent that this missing override type annotations error was only meant as a lint warning to aid a Google-internal migration effort, not OSS hard compile error.

**Comment by brad4d** [comment]
This is working as intended. Effectively the command line option asked the compiler to treat all messages as fatal errors, and that is what it did.

We would be willing to consider a PR that makes it easier to say "everything except lint errors", but we don't expect to spend development time on this ourselves.

**Comment by vapier** [comment]
I think you're missing the point.  the problem isn't that it failed (exited non-zero) after displaying diagnostics, the problem is that it displayed a diagnostic in the first place.  closure-compiler used to treat `@override` as "inherit the settings from the overridden function".  it doesn't do that anymore.  the base class is correctly annotated in my example.

this is also what the documentation still claims closure-compiler will do.

at this point i've made piece with closure-compiler not being useful for OSS purposes (i.e. external to Google), and no one should use/adopt it for any project.  it's still years behind ES standards.  migrating an existing/mature code base to tsc will be painful, but it's the only option.

**Comment by lauraharker** [comment]
The compiler does still attempt to copy typings from superclasses - for example, see this [closure-compiler-debugger link](https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Parent%2520%257B%250A%2520%2520%252F**%2520%2540return%2520%257Bstring%257Cnumber%257D%2520*%252F%250A%2520%2520method()%2520%257B%250A%2520%2520%2520%2520return%25200%253B%250A%2520%2520%257D%250A%257D%250A%250Aclass%2520Child%2520extends%2520Parent%2520%257B%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520method()%2520%257B%250A%2520%2520%2520%2520return%2520null%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26REWRITE_MODULES_BEFORE_TYPECHECKING%3Dtrue%26CLOSURE_PASS%3Dtrue%26PARSE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue).

``` js
class Parent {
  /** @return {string|number} */
  method() {
    return 0;
  }
}

class Child extends Parent {
  /** @override */
  method() {
    return null;
  }
}
```

This produces:

```
input0:11:11: WARNING - [JSC_TYPE_MISMATCH] inconsistent return type
found   : null
required: (number|string)
  11|     return null;
                 ^^^^
```

All that changed is that internally at Google, we decided we wanted to nudge people not to rely on this copying, so we added a lint warning. The actual type copying behavior is unchanged.

**Comment by shicks** [comment]
To clarify - the reason this change was made was because of (not so) recent work to make compilation faster and more incremental.  To do incremental builds successfully, the compiler needs the additional explicit types, so we added the warning to ensure we weren't losing types on incremental builds.

That said, given that this is an internal requirement, we should definitely make it possible to silence it, or maybe even change the external default.

I'm sorry your experience with using Closure externally has been so frustrating.  Depending on your needs, migrating to TypeScript might be the best option.  Since we started moving toward TypeScript internally, there's been a lot less motivation to improve the type checking side of things beyond what's required for good optimization, and we don't really see much value in trying to maintain the Closure type system when most users would be better served by migrating to TypeScript and using a more mainstream optimizer.  As long as you're not trying to DCE massive amounts of protobuf gencode, most external optimizers are usually plenty good.

EDIT: I meant to add that if there's an existing diagnostic group that includes the warnings you want to silence, you can already use it with `--jscomp_error=* --jscomp_off=<whatever>`.  But looking at the list of error groups, I didn't see one that looked promising.  It's not too hard to add a new one if that's what's needed.

**Comment by brad4d** [comment]
Actually, it looks to me like the specific error listed as a problem here is already included in the group with the name "lintChecks", so it should work to do `--jscomp_error=* --jscomp_off=lintChecks`

https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/lint/CheckJSDocStyle.java#L104
shows the warning being added to a `CheckJSDocStyle.LINT_DIAGNOSTICS`.

https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/DiagnosticGroups.java#L556
shows `CheckJSDocStyle.LINT_DIAGNOSTICS` being added to the group registered under the name `"lintChecks"`.
