### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by mprobst** [google/closure-compiler#3823]
See here: https://github.com/google/closure-compiler/runs/2665297844?check_suite_focus=true

```
warning: -parameters is not supported for target value 1.7. Use 1.8 or later.
ERROR: /home/runner/work/closure-compiler/closure-compiler/BUILD.bazel:100:1: Building libcompiler_lib-class.jar (766 source files) and running annotation processors (AutoAnnotationProcessor, AutoOneOfProcessor, AutoValueProcessor) failed (Exit 1)
src/com/google/javascript/jscomp/Linter.java:27: error: package com.google.javascript.refactoring does not exist
import com.google.javascript.refactoring.ApplySuggestedFixes;
                                        ^
src/com/google/javascript/jscomp/Linter.java:28: error: package com.google.javascript.refactoring does not exist
import com.google.javascript.refactoring.FixingErrorManager;
                                        ^
src/com/google/javascript/jscomp/Linter.java:29: error: package com.google.javascript.refactoring does not exist
import com.google.javascript.refactoring.SuggestedFix;
                                        ^
INFO: Elapsed time: 246.925s, Critical Path: 43.29s
INFO: 237 processes: 217 local, 20 worker.
FAILED: Build did NOT complete successfully
```

It's unclear to me why - this code appears to have been around for a long time, and I don't know how to tell what the exact changeset for this build was. Maybe it's just a BUILD file change gone wrong?

**Comment by brad4d** [comment]
Thanks for pointing this out.

I've rolled back the offending change and the build is fine now.
