### ISSUE TITLE
Undocumented breaking change in v20170423: missing externs?

### ISSUE THREAD

**Issue by alexeagle** [google/closure-compiler#2487]
Reported in 
https://github.com/alexeagle/closure-compiler-angular-bundling/issues/30#issuecomment-300364464:

Upgrading from v20170409 to v20170423 breaks my program:
```
node_modules/@angular/core/@angular/core.js:5607: ERROR - variable System is undeclared
        return System.import(module)
               ^^^^^^

node_modules/@angular/platform-browser/@angular/platform-browser.js:3091: ERROR - variable Hammer is undeclared
        const /** @type {?} */ mc = new Hammer(element);
                                        ^^^^^^

node_modules/moment/moment.js:8: ERROR - variable module is undeclared
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
                                          ^^^^^^

node_modules/moment/moment.js:9: ERROR - variable define is undeclared
    typeof define === 'function' && define.amd ? define(factory) :
           ^^^^^^

node_modules/moment/moment.js:399: ERROR - variable require is undeclared
                require('./locale/' + name);
                ^^^^^^^

node_modules/rxjs/util/root.js:8: ERROR - variable global is undeclared
else if (typeof global == 'object' && global.global === global) {
                ^^^^^^
```

**Comment by ChadKillingsworth** [comment]
Possibly related to #2480

**Comment by MatrixFrog** [comment]
As far as I can tell we don't have any externs for System.import so that should have failed before, at least that first error. Maybe the default level (error/warning/off) of something changed.

**Comment by ChadKillingsworth** [comment]
In the changelog:

> Support compilation of programs with missing definitions.

What's that? I'm not familiar with that change.

**Comment by MatrixFrog** [comment]
I think that's referring to https://github.com/google/closure-compiler/commit/697e52a631df6abe5a4106307e5db2ccb94c19bb by @mprobst

**Comment by ChadKillingsworth** [comment]
So I'm wondering if that change assumed that unknown types were already being warned. Git bisect would tell us for sure - I just don't have time to run it this week.

**Comment by mprobst** [comment]
My change was tested quite a bit against the Google-internal code base. AFAICT it should not cause these kinds of errors (then again, you never quite know...).

**Comment by alexeagle** [comment]
FWIW, using the previous working version of the compiler none of these appeared in the warnings.
https://circleci.com/gh/alexeagle/closure-compiler-angular-bundling/83 is a build with the warnings enabled.

**Comment by erdemapaydin** [comment]
the same problem still persists with v20170521.

the latest https://github.com/angular/closure-demo does not compile with closure giving same output as v20170423:

```
node_modules/@angular/core/@angular/core.js:5447: ERROR - variable System is undeclared
        return System.import(module)
               ^^^^^^

node_modules/@angular/platform-browser/@angular/platform-browser.js:3096: ERROR - variable Hammer is undeclared
        const /** @type {?} */ mc = new Hammer(element);
                                        ^^^^^^

node_modules/rxjs/util/root.js:8: ERROR - variable global is undeclared
var __global = typeof global !== 'undefined' && global;
                      ^^^^^^

```

**Comment by MatrixFrog** [comment]
Someone will probably need to do a 'git bisect' and find which commit broke this.

**Comment by ChadKillingsworth** [comment]
It's definitely clear that addition checks were turned on for specific flag combinations, but I've seen nothing to say that the warnings are wrong.

**Comment by erdemapaydin** [comment]
when symbols check is disabled it works with the newest releases of the compiler.

https://github.com/google/closure-compiler/commit/4c7aaa8a86b1bf4d40ac6c78139394797e88b3b3

**Comment by alexeagle** [comment]
Thanks for tracking this down @erdemapaydin !
@MatrixFrog is the right fix to add these to the standard externs?

**Comment by MatrixFrog** [comment]
What would we be adding? If it's just `System.import` and `global` I believe those are both part of the standard (or will be soon) so that sounds good.

**Comment by ChadKillingsworth** [comment]
`global` is part of the standard. That needs added as `const global = window` in the browser environment externs (not the language externs - at least until we fix the compiler).

`System.import` is NOT a standard. It won't be added in the future either. That should be a custom export.

`module` and `define` are both custom externs and not part of the browser environment. They would need to be custom externs. Defining the `module` extern will break the common JS rewriting.

**Comment by simonsarris** [comment]
Why was this closed? Is the original issue, e.g.

```
node_modules/rxjs/util/root.js:8: ERROR - variable global is undeclared
else if (typeof global == 'object' && global.global === global) {
                ^^^^^^
```

No long a problem?

**Comment by hallya** [comment]
Yeah its still a problem..

**Comment by tjgq** [comment]
The issue you're replying to is still open, but it references issues elsewhere that are themselves closed.

My understanding of the issue is that some Angular code contains references to undeclared symbols. The fix is to provide externs definitions for those symbols.

None of the symbols are part of an ECMAScript or browser spec, so we can't add them to the standard externs. (Incidentally, there's a [stage 3 proposal](https://github.com/tc39/proposal-global) to add `globalThis`.)

I don't think there's anything to do on the compiler side, so I'm going to close this issue. Feel free to reopen if I'm mistaken.
